---
title: "Hockey Season 1718"
author: "Alex Tin"
date: "5/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Desktop/shinyproject/hockey1718")
```

Libraries
```{r}
library(shiny)
library(shinydashboard)
library(ggplot2)
library(dplyr)
library(data.table)
library(plotly)
library(data.table)
library(DT)
library(tidyverse)
library(corrplot)

```

Load all the necessary files (4 total)
```{r}


#data for advanced stats for players in regular season
playerreg <- read_csv(file ="./data/NHLRegular_Total.csv")
playerreg <- playerreg[,0:204]

#data for team stats in regular season
teamreg <- read_csv(file='./data/NHLReg.csv',col_names = TRUE)

#data for player stats in playoffs (basic) - convert to team stats
teamplayoff <- read_csv(file='./data/NHLPlayoffs_Basic.csv',col_names=TRUE)

#data for player stats in playoffs (advanced) - convert to team stats
teamplayoffadv <- read_csv(file='./data/NHLPlayoffs_Advanced.csv',col_names=TRUE)


team2010_2019 <- read_csv(file='./data/Team2010_2019.csv',col_names=TRUE)

```


Regular Season Tab

Regular Season Player Table 
```{r}

# selecting the stats to compare
playertbl = playerreg %>% select(
    .,
    'DftYr',
    'Age',
    'Seasons',
    'H-Ref Name',
    'Team',
    'GP',
    'G',
    'A',
    'CPP',
    'CriG',
    'CruG',
    'CruA1',
    'CruA2',
    'MGL'
)

# Teams for each division
Atlantic = c('BOS','TBL','TOR','FLA','MTL','BUF','OTT','DET')
Metro = c('WSH','PHI','PIT','CAR','CBJ','NYI','NYR','NJD')
Central = c('STL','COL','DAL','WPG','NSH','MIN','CHI')
Pacific = c('VEG','EDM','CGY','VAN','ARI','ANA','LAK','SJS')

#Adding Divisions to player stats
playertbl <- playertbl %>% mutate(., Division = ifelse(Team %in% Atlantic,'Atlantic', ifelse(Team %in% Metro, 'Metropolitan', ifelse(Team %in% Central, 'Central','Pacific'))))

```


Regular Season Team Comparison table
```{r}
#Player statistic comparison

#adding Divisions to team 
teamregtbl <- teamreg %>% mutate(., Division = ifelse(Team %in% Atlantic,'Atlantic', ifelse(Team %in% Metro, 'Metropolitan', ifelse(Team %in% Central, 'Central','Pacific'))))

teamregtbl


```


Playoff Tab

Playoff stats
```{r}
###Manipulate colnames of stats

#add identifier as playoff stats ('playoff_'), and convert to lowercase
colnames(teamplayoff) <- paste0('playoff_',tolower(colnames(teamplayoff)))

#add identifier as playoff stats ('playoff_'), and convert to lowercase
colnames(teamplayoffadv) <- paste0('playoff_',tolower(colnames(teamplayoffadv)))

#remove duplicate column except for identifier to merge with teamplay
teamplayoffadvfin <- subset(teamplayoffadv,select=-c(playoff_rk,playoff_x3, playoff_player,playoff_age,playoff_tm,playoff_pos,playoff_gp))

#merge teamplayoffs
playofftotal <- bind_cols(teamplayoff, teamplayoffadvfin)

#add divisions
playofftotal <- playofftotal %>% mutate(., division = ifelse(playoff_tm %in% Atlantic,'Atlantic', ifelse(playoff_tm %in% Metro, 'Metropolitan', ifelse(playoff_tm %in% Central, 'Central','Pacific'))))




# Team statistics
# teamstat <- regtbl %>% group_by(., Division, Team) %>% summarise(., agg_goals = sum(G), agg_clean = sum(CPP))
# 
# teamstat
# teamstat %>% ggplot(aes(x=agg_goals,y=agg_clean,label=Team)) + geom_point(aes(color=Division))
# 
# 
# meangoals = mean(regtbl$agggoals)
# 
# teamstat %>% mutate(., difftoavg= lapply(agggoals, function(x) x-meangoals))
# 


#Provided by <a href="https://www.sports-reference.com/sharing.html?utm_source=direct&utm_medium=Share&utm_campaign=ShareTool">Hockey-Reference.com</a>: <a href="https://www.hockey-reference.com/leagues/NHL_2018.html?sr&utm_source=direct&utm_medium=Share&utm_campaign=ShareTool#stats_adv">View Original Table</a><br>Generated 5/8/2020.
```


Team Stats

```{r}

# Group by season


# Plotting champions of each year
champs1019 <- team2010_2019[team2010_2019$`Eventual Champion` ==1,]


# Avg Team stat
avgseasonstat = team2010_2019 %>% group_by(., Season) %>% summarise_all(., mean)

avgseasonstat = subset(avgseasonstat, select = -c(Tm, `Eventual Champion`))

avgseasonstat



ggplot(avgseasonstat, aes(x=Season, ))

```


Correlation matrix

```{r}

corrseasonstat <- subset(avgseasonstat, select = -c(Season, Rk))
corrseasonstat/82
corrseasontable = cor(corrseasonstat)

```


Corrplot

```{r}

corrplot(corrseasontable)


```








